function Mainmenuopen()
    if CLIENT then
        RunConsoleCommand("Kill")
        end
    local scrw, scrh = ScrW(), ScrH()
    Mainmenu = vgui.Create("DFrame")
    Mainmenu:SetSize(scrw, scrh)
    Mainmenu:Center()
    Mainmenu:SetTitle("")
    Mainmenu:MakePopup()
    Mainmenu:SetDraggable(false)
    Mainmenu:ShowCloseButton(false)
    Mainmenu.Paint = function (me,w,h)
        surface.SetDrawColor(0,0,0,200)
        surface.DrawRect(0,0,w,h)
    end
    Menuclose = vgui.Create("DButton", Mainmenu)
    Menuclose:SetText("Close")
    Menuclose:Center()
    Menuclose:SetMouseInputEnabled(true)
    Menuclose:SetSize(scrw * .1, scrh * .1)
    Menuclose:SetPos(scrw - scrw/1.8, scrh - scrh/4)
    function Menuclose:DoClick()
        Mainmenu:Close()
        end
    Settingsbutton = vgui.Create("DButton", Mainmenu)
    Settingsbutton:SetText("Settings")
    Settingsbutton:Center()
    Settingsbutton:SetMouseInputEnabled(true)
    Settingsbutton:SetSize(scrw *.1, scrh *.1)
    Settingsbutton:SetPos(scrw - scrw/1.8, scrh - scrh/2.8)
    function Settingsbutton:DoClick()
        Mainmenu:Close()
        Settingsmenu = vgui.Create("DFrame")
        Settingsmenu:SetSize(scrw, scrh)
    Settingsmenu:Center()
    Settingsmenu:SetTitle("")
    Settingsmenu:MakePopup()
    Settingsmenu:SetDraggable(false)
    Settingsmenu:ShowCloseButton(false)
    Settingsmenu.Paint = function (me,w,h)
        surface.SetDrawColor(0,0,0,200)
        surface.DrawRect(0,0,w,h)
        draw.SimpleText("Weapon Font Size", "DermaLarge", scrw - scrw/1, scrh - scrh/3.4, Color(255,255,255,255), TEXT_ALIGN_LEFT, TEXT_ALIGN_LEFT)
        end
        Wepfontsizeselector = vgui.Create("DNumSlider", Settingsmenu)
        Wepfontsizeselector:SetMin(1)
        Wepfontsizeselector:SetMax(200)
        Wepfontsizeselector:SetDefaultValue(75)
        Wepfontsizeselector:SetConVar("Wepfontsize")
        Wepfontsizeselector:SetSize(scrw *.3, scrh * .1)
        Wepfontsizeselector:SetPos(scrw - scrw/1, scrh - scrh/3)
        SettingsMenuClose = vgui.Create("DButton", Settingsmenu)
        SettingsMenuClose:SetText("Close")
        SettingsMenuClose:Center()
        SettingsMenuClose:SetMouseInputEnabled(true)
        SettingsMenuClose:SetSize(scrw * .1, scrh * .1)
        SettingsMenuClose:SetPos(scrw - scrw/1.8, scrh - scrh/4)
        function SettingsMenuClose:DoClick()
            Settingsmenu:Close()
            if CLIENT then
                RunConsoleCommand("Mainmenu")
            end
            end
    end
    Customizationbutton = vgui.Create("DButton", Mainmenu)
    Customizationbutton:SetText("Customization")
    Customizationbutton:Center()
    Customizationbutton:SetMouseInputEnabled(true)
    Customizationbutton:SetSize(scrw *.1, scrh *.1)
    Customizationbutton:SetPos(scrw - scrw/1.8, scrh - scrh/2.15)
    function Customizationbutton:DoClick()
        Mainmenu:Close()
        Customizationmenu = vgui.Create("DFrame")
        Customizationmenu:SetSize(scrw, scrh)
        Customizationmenu:Center()
        Customizationmenu:SetTitle("")
        Customizationmenu:MakePopup()
        Customizationmenu:SetDraggable(false)
        Customizationmenu:ShowCloseButton(false)
        Customizationmenu.Paint = function (me,w,h)
        surface.SetDrawColor(0,0,0,200)
        surface.DrawRect(0,0,w,h)
        draw.SimpleText("Red Blood", "DermaLarge", scrw - scrw/1.03, scrh - scrh/2.93, Color(255,255,255,255), TEXT_ALIGN_LEFT, TEXT_ALIGN_LEFT)
    end
    Redbloodcheck = vgui.Create("DCheckBox", Customizationmenu) -- I don't think this works yet but I'll make it work later
    Redbloodcheck:SetSize(scrw *.01, scrh * .01)
    Redbloodcheck:SetPos(scrw - scrw/1.1, scrh - scrh/3)
    if Redbloodcheck:GetChecked() == true then
            Player:SetBloodColor(0)
    else
    end
    Customizationmenuclose = vgui.Create("DButton", Customizationmenu)
    Customizationmenuclose:SetText("Close")
    Customizationmenuclose:Center()
    Customizationmenuclose:SetMouseInputEnabled(true)
    Customizationmenuclose:SetSize(scrw * .1, scrh * .1)
    Customizationmenuclose:SetPos(scrw - scrw/1.8, scrh - scrh/4)
        function Customizationmenuclose:DoClick()
            Customizationmenu:Close()
            if CLIENT then
                RunConsoleCommand("Mainmenu")
            end
            end
end
    Statsbutton = vgui.Create("DButton", Mainmenu)
    Statsbutton:SetText("Stats")
    Statsbutton:Center()
    Statsbutton:SetMouseInputEnabled(true)
    Statsbutton:SetSize(scrw *.1, scrh *.1)
    Statsbutton:SetPos(scrw - scrw/1.8, scrh - scrh/1.75)
    function Statsbutton:DoClick()
        Mainmenu:Close()
        Statsmenu = vgui.Create("DFrame")
        Statsmenu:SetSize(scrw, scrh)
        Statsmenu:Center()
        Statsmenu:SetTitle("")
        Statsmenu:MakePopup()
        Statsmenu:SetDraggable(false)
        Statsmenu:ShowCloseButton(false)
        Statsmenu.Paint = function (me,w,h)
        surface.SetDrawColor(0,0,0,200)
        surface.DrawRect(0,0,w,h)
        end
        Statsmenuclose = vgui.Create("DButton", Statsmenu)
        Statsmenuclose:SetText("Close")
        Statsmenuclose:Center()
        Statsmenuclose:SetMouseInputEnabled(true)
        Statsmenuclose:SetSize(scrw * .1, scrh * .1)
        Statsmenuclose:SetPos(scrw - scrw/1.8, scrh - scrh/4)
        function Statsmenuclose:DoClick()
            Statsmenu:Close()
            if CLIENT then
                RunConsoleCommand("Mainmenu")
            end
            end
            end
end
concommand.Add("Mainmenu", Mainmenuopen) -- commands stop working when in consolecmds.lua so I'm putting them here too
concommand.Add("WepFontApply", WepFontMaker)
concommand.Add("SbFontApply", SbFontMaker)