function Mainmenuopen()
    if CLIENT then
        RunConsoleCommand("Mainmenuspec")
        RunConsoleCommand("Remitems")
        end
    local scrw, scrh = ScrW(), ScrH()
    Mainmenu = vgui.Create("DFrame")
    Mainmenu:SetSize(scrw, scrh)
    Mainmenu:Center()
    Mainmenu:SetTitle("")
    Mainmenu:MakePopup()
    Mainmenu:SetDraggable(false)
    Mainmenu:ShowCloseButton(false)
    Mainmenu.Paint = function (me,w,h)
        surface.SetDrawColor(0,0,0,200)
        surface.DrawRect(0,0,w,h)
    end
    Menuclose = vgui.Create("DButton", Mainmenu)
    Menuclose:SetText("Close")
    Menuclose:Center()
    Menuclose:SetMouseInputEnabled(true)
    Menuclose:SetSize(scrw * .1, scrh * .1)
    Menuclose:SetPos(scrw - scrw/1.8, scrh - scrh/4)
    function Menuclose:DoClick()
        Mainmenu:Close()
        if CLIENT then
            RunConsoleCommand("Unspec")
            RunConsoleCommand("Kill")
        end
        end
    Settingsbutton = vgui.Create("DButton", Mainmenu)
    Settingsbutton:SetText("Settings")
    Settingsbutton:Center()
    Settingsbutton:SetMouseInputEnabled(true)
    Settingsbutton:SetSize(scrw *.1, scrh *.1)
    Settingsbutton:SetPos(scrw - scrw/1.8, scrh - scrh/2.8)
    function Settingsbutton:DoClick()
        Mainmenu:Close()
        Settingsmenu = vgui.Create("DFrame")
        Settingsmenu:SetSize(scrw, scrh)
    Settingsmenu:Center()
    Settingsmenu:SetTitle("")
    Settingsmenu:MakePopup()
    Settingsmenu:SetDraggable(false)
    Settingsmenu:ShowCloseButton(false)
    Settingsmenu.Paint = function (me,w,h)
        surface.SetDrawColor(0,0,0,200)
        surface.DrawRect(0,0,w,h)
        end
        SettingsMenuClose = vgui.Create("DButton", Settingsmenu)
        SettingsMenuClose:SetText("Close")
        SettingsMenuClose:Center()
        SettingsMenuClose:SetMouseInputEnabled(true)
        SettingsMenuClose:SetSize(scrw * .1, scrh * .1)
        SettingsMenuClose:SetPos(scrw - scrw/1.8, scrh - scrh/4)
        function SettingsMenuClose:DoClick()
            Settingsmenu:Close()
            if CLIENT then
                RunConsoleCommand("Mainmenu")
            end
            end
    end
    Customizationbutton = vgui.Create("DButton", Mainmenu)
    Customizationbutton:SetText("Customization")
    Customizationbutton:Center()
    Customizationbutton:SetMouseInputEnabled(true)
    Customizationbutton:SetSize(scrw *.1, scrh *.1)
    Customizationbutton:SetPos(scrw - scrw/1.8, scrh - scrh/2.15)
    function Customizationbutton:DoClick()
        Mainmenu:Close()
        Customizationmenu = vgui.Create("DFrame")
        Customizationmenu:SetSize(scrw, scrh)
        Customizationmenu:Center()
        Customizationmenu:SetTitle("")
        Customizationmenu:MakePopup()
        Customizationmenu:SetDraggable(false)
        Customizationmenu:ShowCloseButton(false)
        Customizationmenu.Paint = function (me,w,h)
        surface.SetDrawColor(0,0,0,200)
        surface.DrawRect(0,0,w,h)
    end
    Customizationmenuclose = vgui.Create("DButton", Customizationmenu)
    Customizationmenuclose:SetText("Close")
    Customizationmenuclose:Center()
    Customizationmenuclose:SetMouseInputEnabled(true)
    Customizationmenuclose:SetSize(scrw * .1, scrh * .1)
    Customizationmenuclose:SetPos(scrw - scrw/1.8, scrh - scrh/4)
        function Customizationmenuclose:DoClick()
            Customizationmenu:Close()
            if CLIENT then
                RunConsoleCommand("Mainmenu")
            end
            end
end
end
concommand.Add("Mainmenu", Mainmenuopen)